#!/bin/bash

echo "🚀 Deploying upload-bank-transfer API..."
echo ""

echo "📋 API Details:"
echo "   - Endpoint: /backend/api/upload-bank-transfer/"
echo "   - Method: POST"
echo "   - Function: Upload ảnh chuyển khoản lên Cloudinary"
echo "   - Max file size: 10MB"
echo "   - Allowed formats: PNG, JPG, JPEG, GIF, WEBP"
echo ""

echo "✅ Changes made:"
echo "   1. Added upload_bank_transfer() function in views.py"
echo "   2. Added URL route in urls.py"
echo "   3. CSRF exempt already configured in settings.py"
echo ""

echo "📤 Manual deployment steps for PythonAnywhere:"
echo ""
echo "1. Copy files to production:"
echo "   - Upload views.py (contains upload_bank_transfer function)"
echo "   - Upload urls.py (contains URL route)"
echo ""
echo "2. Reload Django web app:"
echo "   - Go to PythonAnywhere Web tab"
echo "   - Click 'Reload buddyskincare.vn'"
echo ""
echo "3. Test the endpoint:"
echo "   curl -X POST https://buddyskincare.vn/backend/api/upload-bank-transfer/"
echo ""
echo "4. Test with file upload:"
echo "   curl -X POST -F 'file=@test_image.jpg' https://buddyskincare.vn/backend/api/upload-bank-transfer/"
echo ""
echo "🎯 Expected response:"
echo "   {\"success\": true, \"url\": \"https://res.cloudinary.com/...\", \"public_id\": \"...\"}"
echo ""
echo "✅ API will be available at: https://buddyskincare.vn/backend/api/upload-bank-transfer/"