#!/bin/bash

echo "🚀 Deploying bank transfer upload fix..."
echo ""

echo "📋 Current status:"
echo "   - Django endpoint: /backend/api/upload-bank-transfer/ (404 on production)"
echo "   - Flask endpoint: /api/upload-bank-transfer (404 on production)"
echo "   - But API shows successful uploads in database!"
echo ""

echo "🔍 Diagnosis:"
echo "   - Endpoints were working before (data exists)"
echo "   - Current 404 suggests deployment issue"
echo "   - Need to check if code is properly deployed"
echo ""

echo "📤 Manual deployment steps for PythonAnywhere:"
echo ""
echo "1. Check if files are deployed:"
echo "   ls -la /home/buddyskincare/websitemypham/views.py"
echo "   ls -la /home/buddyskincare/websitemypham/urls.py"
echo ""
echo "2. Check Django URL patterns:"
echo "   grep -n 'upload-bank-transfer' /home/buddyskincare/websitemypham/urls.py"
echo ""
echo "3. Check Django view function:"
echo "   grep -n 'def upload_bank_transfer' /home/buddyskincare/websitemypham/views.py"
echo ""
echo "4. Reload Django web app:"
echo "   - Go to PythonAnywhere Web tab"
echo "   - Click 'Reload buddyskincare.vn'"
echo ""
echo "5. Test endpoint after reload:"
echo "   curl -X POST https://buddyskincare.vn/backend/api/upload-bank-transfer/"
echo ""
echo "✅ This should restore the working upload functionality!"