"""
Django settings for BuddyProject project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import os

# Cloudinary configuration
import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config(
    cloud_name="deoknys7k",
    api_key="657643869681298",
    api_secret="K8pAAJPmIUcO7ThRnfOtJx7Ntwg"
)

BASE_DIR = Path(__file__).resolve().parent.parent
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

from datetime import timedelta
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e7f$b$k49bk6m!)yh5=fp0a*4o1nsxv97h&bt5e=pov2t)el00'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CSRF_EXEMPT_PATHS = [
    'https://buddyskincare.vn/backend/api/auth/google/', # Hoặc đường dẫn API cụ thể của bạn
    'https://buddyskincare.vn/backend/api/ctv-applications/',
    'https://buddyskincare.vn/backend/api/upload-bank-transfer/',
    'https://buddyskincare.vn/backend/api/upload-cccd/',
]

APPEND_SLASH = False



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'ckeditor',
    'BuddyApp',
    'drf_yasg',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'oauth2_provider',
    'corsheaders',
    'social_django',
    'django.contrib.humanize',
    'drf_spectacular',
]


CORS_ALLOWED_ORIGINS = [
    "https://buddyskincare.pythonanywhere.com",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://buddyskincare.vn",
    "http://buddyskincare.vn", # Thêm http để test
    "http://localhost:3000", # Nếu bạn dùng React/Vue
]

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'BuddyProject.middleware.CsrfExemptMiddleware', # Thêm middleware mới ở đây
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

# AUTHENTICATION_BACKENDS = [
#     'BuddyApp.backends.PhoneNumberAuthenticationBackend',
#     'django.contrib.auth.backends.ModelBackend',
#     'social_core.backends.google.GoogleOAuth2',

# ]


AUTHENTICATION_BACKENDS = [
    'BuddyApp.backends.IdentifierAuthBackend',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'BuddyProject.urls'


SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
    'openid'
]


# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#                 'social_django.context_processors.backends',
#                 'social_django.context_processors.login_redirect',
#             ],
#         },
#     },
# ]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'websitemypham/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication', # Sử dụng Token Authentication
        'rest_framework.authentication.SessionAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication'# Có thể giữ lại nếu bạn cần
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
        # Mặc định yêu cầu xác thực

    ),
    'DEFAULT_PAGINATION_CLASS': None,  # Tắt pagination mặc định
    'PAGE_SIZE': None,  # Không giới hạn page size
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

WSGI_APPLICATION = 'BuddyProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh' # Hoặc múi giờ phù hợp với server của bạn

USE_I18N = True

USE_TZ = True

ALLOWED_HOSTS = ['buddyskincare.pythonanywhere.com', '127.0.0.1', 'localhost',"buddyskincare.vn"]

CSRF_TRUSTED_ORIGINS = [
    'https://buddyskincare.pythonanywhere.com',
    'https://buddyskincare.vn',
    'https://*.buddyskincare.vn', # Hỗ trợ subdomains
]

CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True
CORS_ALLOW_CREDENTIALS = True





# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# PythonAnywhere static files configuration
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional locations of static files (không được chứa STATIC_ROOT)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files finders
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'buddyskincare$buddydb',
        'USER': 'buddyskincare',
        'PASSWORD': 'Admin@123',
        'HOST': 'buddyskincare.mysql.pythonanywhere-services.com'
    }
}
AUTH_USER_MODEL = 'BuddyApp.User'
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = False


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '821773612134-1u5206jkloc187irc108rqfcrcvb4420.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),  # Giữ nguyên thời gian sống của token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),    # Giữ nguyên thời gian sống của token làm mới
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': 'z(*l)3l@4neyd@yz+b&&e2c7=bl23x$*lz_vtnhh#%m6lcjd=7',
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}
DRFSO2_URL_NAMESPACE = 'oauth2_provider'




# settings.py

# ... các cấu hình khác

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'buddyskincarevn@gmail.com'  # Thay bằng email của bạn
EMAIL_HOST_PASSWORD = 'fkoz aohr yeub fncz'  # Thay bằng mật khẩu ứng dụng
DEFAULT_FROM_EMAIL = 'buddyskincarevn@gmail.com'

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Buddy Skincare API',
    'DESCRIPTION': 'API documentation for Buddy Skincare website',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}




















