# Generated by Django 4.2.7 on 2024-01-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautysale', '0003_add_updated_at_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckyparticipant',
            name='email',
            field=models.EmailField(default='', verbose_name='Email'),
            preserve_default=False,
        ),
    ]